ArticleManage/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : urls.py
    *  @Author : wshu
    *  @CodeDate : 2020/2/16 11:40
    *  @Software : PyCharm
    ***********************************
"""
from django.urls import path

from . import views

urlpatterns = [
    path('user/', views.article_view, name='articleview'),
    path('user/list/', views.article_list, name='articlelist'),
    path('user/details/', views.article_details, name='articledetails'),


    path('user/create/', views.article_create, name='articlecreate'),
]

JQ/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('jqsec/', admin.site.urls),
    path('', include('RBAC.urls')),
    path('notice/', include('NoticeManage.urls')),
    path('article/', include('ArticleManage.urls')),
    path('asset/', include('AssetManage.urls')),
    path('task/', include('TaskManage.urls')),
    path('vuln/', include('VulnManage.urls')),
    path('mapped/', include('NetmapManage.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler500 = views.page_error
handler403 = views.permission_denied

ArticleManage/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : models.py
    *  @Author : wshu
    *  @CodeDate : 2019/6/11 9:16
    *  @Software : PyCharm
    ***********************************
"""

from django.db import models

from django.contrib.auth.models import User


ARTICLE_STATUS =(
    ('0', '新建'),
    ('1', '发布'),
    ('2', '撤回'),
    ('3', '审核'),
)


class ArticleType(models.Model):
    """
    文章分类
    """
    article_type_name = models.CharField('文章分类', max_length=30)
    article_type_body = models.TextField('分类简介')
    parent = models.ForeignKey('self', verbose_name=u'父菜单', related_name='articletype_type', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = u'文章分类'

    def __str__(self):
        # 显示顶级菜单
        title_list =[self.article_type_name]
        p = self.parent
        while p:
            title_list.insert(0, p.article_type_name)
            p = p.parent
        return '-'.join(title_list)


class Article(models.Model):
    """
    文章
    """
    article_id = models.CharField('文章ID', max_length=30)
    article_name = models.CharField('文章标题', max_length=50, unique=True)
    article_order = models.IntegerField('文章推广', default=0)
    file = models.FileField('附件', upload_to='article/', null=True, blank=True)
    article_body = models.TextField('文章内容')
    article_status = models.TextField('文章状态',choices=ARTICLE_STATUS,default='0')
    article_starttime = models.DateTimeField('添加时间',auto_now_add=True)
    article_updatetime = models.DateTimeField('更新时间',auto_now=True)
    ##
    article_type = models.ForeignKey(ArticleType,related_name='articletype_for_article',on_delete=models.CASCADE,null=True,verbose_name='文章分类', limit_choices_to={'parent__isnull':False})
    article_user = models.ForeignKey(User,related_name='article_for_user', on_delete=models.CASCADE, null=True,
                                     verbose_name='用户关联')

    class Meta:
        verbose_name_plural = u'文章'

    def __str__(self):
        return self.article_id


class ArticleComment(models.Model):
    """
    评论
    """
    article_comment_id = models.CharField('评论ID', max_length=30)
    article_comment_body = models.TextField('评论内容')
    article_comment_status = models.TextField('评论状态', choices=ARTICLE_STATUS)
    article_comment_starttime = models.DateTimeField('添加时间', auto_now_add=True)

    article_comment_article = models.ForeignKey(Article, related_name='articlecomment_for_article',
                                                on_delete=models.CASCADE, verbose_name='文章关联')
    article_comment_user = models.ForeignKey(User, related_name='articlecomment_for_user', on_delete=models.CASCADE,
                                             verbose_name='用户关联')

    class Meta:
        verbose_name_plural = u'文章'

    def __str__(self):
        return self.article_comment_id

RBAC/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
"""
    ***********************************
    *  @filename : models.py
    *  @Author : wshu
    *  @CodeDate : 18-10-1 上午9:16
    *  @Software : PyCharm
    ***********************************
"""


from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import django.utils.timezone as timezone

class Menu(models.Model):
    """
        菜单表
    """
    title = models.CharField(u'菜单标题', max_length=25, unique=True)
    icon = models.CharField(u'菜单图标', max_length=50)
    parent = models.ForeignKey('self', verbose_name=u'父菜单', related_name='menu_menu', null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '菜单'

    def __str__(self):
        # 显示层级菜单
        title_list = [self.title]
        p = self.parent
        while p:
            title_list.insert(0, p.title)
            p = p.parent
        return '-'.join(title_list)


# 设置访问链接
class Permission(models.Model):
    """
        权限表
    """
    title = models.CharField(u'权限标题', max_length=50, unique=True)
    is_menu = models.BooleanField('菜单显示', default=False)
    url = models.CharField(max_length=128)
    menu = models.ForeignKey(Menu, null=True, verbose_name=u'权限菜单', related_name='permission_menu', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '权限'

    def __str__(self):
        return '{menu}--{permission}'.format(menu=self.menu, permission=self.title)


class Role(models.Model):
    """
        角色表
    """
    title = models.CharField(u'角色名称', max_length=25, unique=True)
    permissions = models.ManyToManyField(Permission, verbose_name=u'权限菜单', related_name='role_permission')
    class Meta:
        verbose_name_plural = '角色'

    def __str__(self):
        return self.title


class Area(models.Model):
    name = models.CharField('属地信息', max_length=90, unique=True)
    parent = models.ForeignKey('self', verbose_name='父级属地', related_name='assetarea_area', null=True, blank=True, on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural = '属地'

    def __str__(self):
        # 显示层级菜单
        title_list = [self.name]
        p = self.parent
        while p:
            title_list.insert(0, p.name)
            p = p.parent
        return '-'.join(title_list)

REQUEST_STATUS=(
    ('0', '待审批'),
    ('1', '审批通过'),
    ('2', '审批拒绝'),
    )
# 注册审批时使用
class UserRequest(models.Model):
    email = models.EmailField('申请邮箱')
    urlarg = models.CharField('注册参数', max_length=50)
    status = models.CharField('审批状态', max_length=50, default='0', choices=REQUEST_STATUS)
    is_check = models.BooleanField('是否审批', default=False)
    is_use = models.BooleanField('是否使用', default=False)
    request_type = models.ForeignKey(Role, verbose_name=u'账号权限', related_name='userrequest_role', on_delete=models.CASCADE)
    starttime = models.DateTimeField('申请时间', auto_now_add=True)
    updatetime = models.DateTimeField('审批时间', auto_now=True)

    area = models.ForeignKey(Area, verbose_name='所属区域', related_name='userrequest_area', null=True,
                             on_delete=models.CASCADE, limit_choices_to={'parent__isnull': True})
    action_user = models.ForeignKey(User, related_name='regist_for_actionuser', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = '注册审批'

    def __str__(self):
        return self.email


#重置密码时使用
class UserResetpsd(models.Model):
    email = models.EmailField('申请邮箱')
    urlarg = models.CharField('重置参数', max_length=50)
    is_check = models.BooleanField('是否使用', default=False)
    updatetime = models.DateField('更新时间', auto_now=True)

    def __str__(self):
        return self.email


# 用户附加属性
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_num = models.CharField(u'员工编号', max_length=50, null=True, blank=True)
    title = models.CharField(u'职位名称', max_length=50)
    telephone = models.CharField(u'座机号码', max_length=50, null=True, blank=True)
    mobilephone = models.CharField(u'手机号码', max_length=50)
    description = models.TextField(u'用户简介')
    error_count = models.IntegerField(u'错误登陆', default=0)
    lock_time = models.DateTimeField(u'锁定时间', default=timezone.now)

    parent_email = models.EmailField('上级邮箱', null=True, blank=True)
    parent = models.ForeignKey(User, verbose_name='上级汇报', related_name='user_parent', null=True, blank=True,
                               on_delete=models.CASCADE)
    area = models.ForeignKey(Area, verbose_name='所属区域', related_name='user_area', null=True, on_delete=models.CASCADE,
                             limit_choices_to={'parent__isnull': True})

    roles = models.ManyToManyField(Role, verbose_name=u'所属角色', related_name='user_role')

    class Meta:
        verbose_name_plural = '用户'

    def __str__(self):
        return self.user.username


# 同步保存信息
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

ArticleManage/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : forms.py
    *  @Author : wshu
    *  @CodeDate : 2019/6/11 10:23
    *  @Software : PyCharm
    ***********************************
"""
from django.forms import ModelForm
from . import models
from django.forms import widgets

class ArticleEditForm(ModelForm):
    class Meta:
        model = models.Article
        fields = ['article_name', 'article_type', 'article_body', 'file']
        widgets = {
            'article_name': widgets.TextInput(attrs={'class': 'form-control', 'placeholder': '文章名称'}),
            'article_type': widgets.Select(attrs={'class': 'form-control'}),
            'article_body': widgets.Textarea(attrs={'class': 'form-control', 'placeholder': '知识库内容'}),
            'file': widgets.FileInput(),
        }

ArticleManage/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : views.py
    *  @Author : wshu
    *  @CodeDate : 2019/6/12 11:42
    *  @Software : PyCharm
    ***********************************
"""
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.utils.dateformat import time_format
from django.utils.html import escape

from . import models, forms
from JQSetting.views import paging

import time
import uuid as sk

################################
# 文章视图
################################
@login_required
def article_view(request):
    article_type = models.ArticleType.objects.filter(parent__isnull=False)
    # print(article_type)
    return render(request, 'ArticleManage/articlelist.html', locals())


################################
# 列表
################################
@login_required
@csrf_protect
def article_list(request):
    return JsonResponse('ok')




################################
# 详情
################################
@csrf_exempt
@login_required
def article_details(request):
    return render(request, 'ArticleManage/articledetails.html')


################################
# 创建
################################
@login_required
@csrf_protect
def article_create(request):
    user = request.user
    error = ''

    if user.is_superuser:
        if request.method == 'POST':
            form = forms.ArticleEditForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    num_id = models.Article.objects.latest('id').id
                except:
                    num_id = 0
                num_id += 1
                article_type = form.cleaned_data['article_type']
                type_id = article_type.id
                article_id = str(type_id) + time.strftime('%Y%m%d', time.localtime(time.time())) + str(num_id)
                article_name = form.cleaned_data['article_name']
                article_type = form.cleaned_data['article_type']
                article_body = form.cleaned_data['article_body']
                file = form.cleaned_data['file']
                if file:
                    file_suffix = file.name.split('.')[-1]
                    file_name = str(sk.uuid1()) + '.' + file_suffix
                    file.name = file_name
                models.Article.objects.get_or_create(
                    article_id=article_id,
                    article_name=article_name,
                    article_type=article_type,
                    article_body=article_body,
                    article_user=user,
                    file=file,
                )
                error = '创建成功'
        else:
            form = forms.ArticleEditForm()
        return render(request, 'formEdit.html', dict(form=form, post_url='articlecreate', error=error))
    else:
        error = '权限错误'
    return render(request, 'error.html', dict(error=error))

templates/ArticleManage/articledetails.html
{% extends 'master.html' %}
<!DOCTYPE html>


{% block master %}
    <h1>文章详情</h1>


{% endblock %}

templates/ArticleManage/articlelist.html
{% extends 'master.html' %}
<!DOCTYPE html>
{% block master %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">知识共享</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <form class="layui-form layui-col-space5">
                        <div class="layui-input-inline layui-show-xs-block">
                            <input type="text" id="id_name" name="name" placeholder="文章名称" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-input-inline layui-show-xs-block">
                            <select class="container" id="id_article_type">
                                <option value="">文章类型</option>
                                {% for item in article_type %}
                                    <option value="{{ item.id }}">{{ item.article_type_name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="layui-input-inline layui-show-xs-block">
                            <select class="container" id="id_article_status">
                                <option value="">文章状态</option>
                                <option value="0">新建</option>
                                <option value="1">发布</option>
                                <option value="2">撤回</option>
                            </select>
                        </div>
                    </form>
                    <div class="layui-input-inline layui-show-xs-block UserTable">
                        <button class="layui-btn" lay-submit="" lay-filter="sreach" data-type="reload">
                            <i class="layui-icon">&#xe615;</i></button>
                    </div>
                </div>
                <xblock>
                    <div class="layui-card-header UserTable">
                        <button type="button" class="layui-btn" onclick="x_admin_show('创建文章', '{% url 'articlecreate' %}')">
                            <i class="layui-icon layui-icon-ok"></i>添加文章
                        </button>
                    </div>
                </xblock>
                <!-- user table-->
                <div class="layui-card-body">
                    <table class="layui-table layui-form" id="article_table"></table>
                </div>
                <!--end user table-->
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
var csrf = $('input[name="csrfmiddlewaretoken"]').val();
layui.use('table', function(){
    var table = layui.table;
    //方法级渲染
    table.render({
        elem: '#article_table'
        ,url: "{% url 'articlelist' %}"
        ,method: 'post'
        ,where: {'csrfmiddlewaretoken':csrf}
        ,cols: [[
            {checkbox: true, fixed: true}
            ,{field: 'article_name', title: '文章标题', sort: true, fixed: true,event:'article'}
            ,{field: 'article_type', title: '文章类型'}
            ,{field: 'updatetime', title: '更新时间', sort: true}
            ,{field: 'article_status', title: '文章状态', sort: true}
            ,{field: 'article_user', title: '文章作者'}
            ,{ title: '高级选项',fixed: 'right', align:'center', toolbar: '#barDemo'}
        ]]
        ,id: 'testReload'
        ,page: true
        ,limit: 15
        ,text:{none: '目前暂无数据'}
    });
});
</script>
{% endblock %}