AssetManage/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
"""
    ***********************************
    *  @filename : urls.py
    *  @Author : wshu
    *  @CodeDate : 19-6-25 下午11:32
    *  @Software : PyCharm
    ***********************************
"""

from django.urls import path

from .views import (views, taskscan, assetdetails, connasset,
                    csv, port)

urlpatterns = [
    # ---资产视图--
    path('user/', views.asset_view, name='assetview'),
    path('user/list', views.asset_list, name='assetlist'),
    path('user/create', views.asset_create, name='assetcreate'),
    path('user/request/', views.asset_request, name='assetrequest'),
    path('user/delete/', views.assetdelete, name='assetdelete'),
    path('user/update/<str:asset_id>/', views.assetupdate, name='assetupdate'),
    path('user/details/<str:asset_id>/', assetdetails.assetdetailsview, name='assetdetails'),

    # ---资产扫描--
    path('user/task/', taskscan.task_action, name='assettaskaction'),

    # ---csv导出--
    path('user/csv/os/', csv.create_csv_os, name='createoscsv'),
    path('user/csv/web/', csv.create_csv_web, name='createwebcsv'),
    path('user/csv/vuln/', csv.create_csv_vuln, name='createvulncsv'),
    path('user/csv/upload/', csv.file_update, name='createuploadcsv'),

    # ---端口综合--
    path('user/port/<str:asset_id>/', assetdetails.asset_ports, name='porttable'),
    path('user/create/port/<str:asset_id>/', port.portcreate, name='portcreate'),
    path('user/update/port/<str:port_id>/', port.portupdate, name='portupdate'),
    path('user/delete/port/<str:port_id>/', port.portdelete, name='portdelete'),

    # ---资产关联--
    path('user/assetconnect/<str:asset_id>/', assetdetails.asset_asset, name='assetconnecttable'),
    path('user/create/assetconnect/<str:asset_id>/', connasset.assetconnectcreate, name='assetconnectcreate'),
    path('user/delete/assetconnect/<str:asset_id>/<str:assetconnect_id>/', connasset.assetconnectdelete,
         name='assetconnectdelete'),
]

JQ/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('jqsec/', admin.site.urls),
    path('', include('RBAC.urls')),
    path('notice/', include('NoticeManage.urls')),
    path('article/', include('ArticleManage.urls')),
    path('asset/', include('AssetManage.urls')),
    path('task/', include('TaskManage.urls')),
    path('vuln/', include('VulnManage.urls')),
    path('mapped/', include('NetmapManage.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler500 = views.page_error
handler403 = views.permission_denied

AssetManage/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
"""
    ***********************************
    *  @filename : models.py
    *  @Author : wshu
    *  @CodeDate : 19-6-23 上午10:45
    *  @Software : PyCharm
    ***********************************
    资产可定制扩展
    例如: 网络设备| 存储设备| 安全设备|
"""

from django.db import models
from django.contrib.auth.models import User
from RBAC.models import Area, REQUEST_STATUS

# Create your models here.

ASSET_REQUEST_ACTION = (
    ('工作交接', '工作交接'),
    ('资产认领', '资产认领'),
)

ASSET_REQUEST_STATUS = (
    ('0', '审批中'),
    ('1', '审批通过'),
    ('2', '审批拒绝'),
)


class Handover(models.Model):
    dst_email = models.EmailField('目标账号')
    status = models.CharField('申请状态', max_length=30, choices=ASSET_REQUEST_STATUS, default='0')
    reason = models.TextField('转让说明')
    action_reason = models.TextField('审批说明')
    request_starttime = models.DateField('添加时间', auto_now_add=True)
    request_updatetime = models.DateField('更新时间', auto_now=True)

    request_user = models.EmailField('申请账号')

    action_user = models.ForeignKey(User, related_name='handover_action_user', on_delete=models.CASCADE, null=True,
                                    blank=True)

    class Meta:
        verbose_name_plural = '资产交接'

    def __str__(self):
        return self.id


class AssetType(models.Model):
    name = models.CharField('资产分类', max_length=30)
    description = models.TextField('资产简介')
    parent = models.ForeignKey('self', verbose_name='父菜单', related_name='assettype_type', null=True, blank=True,
                               on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '资产类型'

    def __str__(self):
        # 显示层级菜单
        return self.name


class AssetTypeInfo(models.Model):
    key = models.CharField('属性标识', max_length=30, unique=True, null=True)
    name = models.CharField('资产属性', max_length=30)
    type_connect = models.ManyToManyField(AssetType, verbose_name='属性关联', related_name='typeinfo_assettype', blank=True)

    class Meta:
        verbose_name_plural = '资产信息'

    def __str__(self):
        return self.name


ASSET_STATUS = (
    ('0', '使用中'),
    ('1', '闲置中'),
    ('2', '已销毁'),
)


class Asset(models.Model):
    asset_id = models.CharField('系统编号', max_length=50, unique=True, null=True)
    asset_out_id = models.CharField('资产编号', max_length=50, null=True, blank=True)
    asset_name = models.CharField('资产名称', max_length=100)
    asset_key = models.CharField('唯一标记', max_length=50, unique=True)
    asset_description = models.TextField('资产介绍', null=True)
    asset_score = models.IntegerField('重要性估值', default='0')
    asset_status = models.CharField('资产状态', max_length=50, choices=ASSET_STATUS, default='0')
    asset_check = models.BooleanField('是否检查', default=False)
    asset_inuse = models.BooleanField('是否认领', default=False)
    asset_starttime = models.DateTimeField('添加时间', auto_now_add=True)
    asset_updatetime = models.DateTimeField('更新时间', auto_now=True)

    user_email = models.EmailField('联系人邮箱', null=True, blank=True)

    asset_area = models.ForeignKey(Area, related_name='area_for_asset', verbose_name='所属区域', on_delete=models.CASCADE,
                                   null=True, blank=True)
    asset_type = models.ForeignKey(AssetType, related_name='type_for_asset', verbose_name='资产类型',
                                   on_delete=models.CASCADE, null=True, limit_choices_to={'parent__isnull': False})
    asset_user = models.ManyToManyField(User, related_name='asset_to_user', blank=True)

    asset_connect = models.ManyToManyField('self', verbose_name='资产关联', related_name='asset_asset', blank=True)

    class Meta:
        verbose_name_plural = '资产'

    def __str__(self):
        return self.asset_key


class AssetRequest(models.Model):
    asset_key = models.CharField('申请对象', max_length=30)
    asset_request_status = models.CharField('状态', max_length=30, choices=REQUEST_STATUS, default='0')
    request_action = models.CharField('操作类型', max_length=30, choices=ASSET_REQUEST_ACTION)
    request_reason = models.TextField('申请理由', null=True)
    request_note = models.TextField('审批备注', null=True)
    request_starttime = models.DateTimeField('添加时间', auto_now_add=True)
    request_updatetime = models.DateTimeField('更新时间', auto_now=True)

    request_user = models.ForeignKey(User, related_name='assetrequest_for_user', on_delete=models.CASCADE)
    asset_type = models.ForeignKey(AssetType, related_name='type_for_assetrequest', verbose_name='资产类型',
                                   on_delete=models.CASCADE, null=True, limit_choices_to={'parent__isnull': False})
    action_user = models.ForeignKey(User, related_name='assetrequestaction_for_user', on_delete=models.CASCADE,
                                    null=True, blank=True)

    class Meta:
        verbose_name_plural = '资产申请'

    def __str__(self):
        return self.asset_key


WEB_LANGUAGE = (
    ('C/C++', 'C/C++'),
    ('C#', 'C#'),
    ('Ruby', 'Ruby'),
    ('JAVA', 'JAVA'),
    ('ASP.NET', 'ASP.NET'),
    ('JSP', 'JSP'),
    ('PHP', 'PHP'),
    ('Perl', 'Perl'),
    ('Python', 'Python'),
    ('VB.NET', 'VB.NET'),
    ('Other', 'Other'),
)

WEB_STATUS = (
    ('0', '测试系统'),
    ('1', '演示系统'),
    ('3', '内部使用'),
    ('4', '商用系统'),
)


class OS_Info(models.Model):
    hostname = models.CharField(max_length=50, verbose_name="主机名")
    os = models.CharField("操作系统", max_length=100, blank=True)
    vendor = models.CharField("设备厂商", max_length=50, blank=True)
    cpu_model = models.CharField("CPU型号", max_length=100, blank=True)
    cpu_num = models.CharField("CPU数量", max_length=100, blank=True)
    memory = models.CharField("内存大小", max_length=30, blank=True)
    disk = models.CharField("硬盘大小", max_length=255, blank=True)
    monitor = models.CharField("监控关联", max_length=30, blank=True)
    sn = models.CharField("SN号 码", max_length=60, blank=True)
    cabinet = models.CharField("机柜信息", max_length=50, blank=True)

    up_time = models.DateField("上架时间", null=True)
    guarante_time = models.DateField("保修时间", null=True)
    down_time = models.DateField("停用时间", null=True)
    updatetime = models.DateField('更新时间', auto_now=True)

    asset = models.OneToOneField(Asset, related_name='os_for_asset', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '系统信息'

    def __str__(self):
        return self.asset.asset_key


class Internet_Info(models.Model):
    middleware = models.CharField('中间件', max_length=50, blank=True, null=True)
    middleware_version = models.CharField('版本', max_length=50, blank=True, null=True)
    is_out = models.BooleanField('是否发布', default=False)
    out_key = models.CharField('域名', max_length=50, blank=True, null=True)
    web_status = models.CharField('状态说明', max_length=50, choices=WEB_STATUS, default='测试系统')
    language = models.CharField('开发语言', max_length=50, choices=WEB_LANGUAGE, null=True)
    language_version = models.CharField('语言版本', max_length=50, blank=True, null=True)
    web_framwork = models.CharField('开发框架', max_length=50, blank=True, null=True)
    web_framwork_version = models.CharField('开发框架版本', max_length=50, blank=True, null=True)
    updatetime = models.DateField('更新时间', auto_now=True)

    asset = models.OneToOneField(Asset, related_name='internet_for_asset', on_delete=models.CASCADE)


    def __str__(self):
        return self.asset.asset_key


class Port_Info(models.Model):
    port = models.CharField('开放端口', max_length=50)
    name = models.CharField('服务名称', max_length=50, null=True)
    product = models.CharField('产品信息', max_length=100, null=True)
    version = models.CharField('应用版本', max_length=50, null=True)
    port_info = models.TextField('端口介绍', null=True)
    updatetime = models.DateField('更新时间', auto_now=True)

    asset = models.ForeignKey(Asset, related_name='port_for_asset', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '端口信息'
    def __str__(self):
        return self.port


class Plugin_Info(models.Model):
    name = models.CharField('组件名称', max_length=50)
    version = models.CharField('应用版本', max_length=50, null=True)
    plugin_info = models.TextField('组件简介', null=True)
    starttime = models.DateTimeField('添加时间', auto_now_add=True)
    updatetime = models.DateField('更新时间', auto_now=True)

    asset = models.ForeignKey(Asset, related_name='plugin_for_asset', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '插件'

    def __str__(self):
        return self.name


class File(models.Model):
    name = models.CharField('附件名称', max_length=50)
    file = models.FileField('附件内容', upload_to='assetfiles/%Y/%m/%d/')
    file_info = models.TextField('附件说明', null=True)
    updatetime = models.DateField('更新时间', auto_now=True)

    asset = models.ForeignKey(Asset, related_name='file_for_asset', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = '附件'

    def __str__(self):
        return self.name


class AssetUser(models.Model):
    dst_user_email = models.EmailField('目标账号')
    reason = models.TextField('指定说明')
    asset_list = models.TextField('资产列表')
    request_updatetime = models.DateField('更新时间', auto_now=True)

    action_user = models.ForeignKey(User, related_name='assetuser_action_user', on_delete=models.CASCADE, null=True,
                                    blank=True)

    class Meta:
        verbose_name_plural = '资产用户'

    def __str__(self):
        return self.dst_user_email



'''
class SecurityDevice(models.Model):
    pass
    
'''

AssetManage/views/connasset.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : connasset.py
    *  @Author : wshu
    *  @CodeDate : 2020/3/23 10:16
    *  @Software : PyCharm
    ***********************************
    资产关联
"""
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.http import JsonResponse

from .. import forms, models
################################
# 资产关联创建
################################
@login_required
@csrf_protect
def assetconnectcreate(request,asset_id):
    user = request.user
    error =''
    if request.method == 'POST':
        form = forms.Asset_connect_form(request.POST)
        if form.is_valid():
            asset_key = form.cleaned_data['asset_key']
            if user.is_superuser:
                asset = get_object_or_404(models.Asset, asset_id=asset_id)
                asset_get = get_object_or_404(models.Asset, asset_key=asset_key)
            else:
                asset = get_object_or_404(models.Asset, asset_user=user, asset_id=asset_id)
                asset_get = get_object_or_404(models.Asset, asset_user=user, asset_key=asset_key)
            asset.asset_connect.add(asset_get)
            asset.save()
            error = '关联成功'
        else:
            error = '请检查输入'
    else:
        form = forms.Asset_connect_form()
    return render(request, 'formupdate.html', {'form': form, 'post_url': 'assetconnectcreate','argu': asset_id,'error': error})


################################
# 资产关联删除
################################
@login_required
def assetconnectdelete(request, asset_id, assetconnect_id):
    user = request.user
    error =''
    if user.is_superuser:
        asset = get_object_or_404(models.Asset, asset_id=asset_id)
        asset_get = get_object_or_404(models.Asset, asset_id=assetconnect_id)
    else:
        asset = get_object_or_404(models.Asset,asset_user=user, asset_id=asset_id)
        asset_get = get_object_or_404(models.Asset,asset_user=user, asset_id=assetconnect_id)
    if asset_get:
        asset.asset_connect.remove(asset_get)
        asset.save()
        error = '删除成功'
    else:
        error = '非法参数'
    return JsonResponse(dict(error=error))

AssetManage/views/file.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : file.py
    *  @Author : wshu
    *  @CodeDate : 2020/3/23 10:55
    *  @Software : PyCharm
    ***********************************
"""

AssetManage/views/taskscan.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'wshu'
__version__ = '1.0'
"""
    ***********************************
    *  @filename : taskscan.py
    *  @Author : wshu
    *  @CodeDate : 2020/3/20 16:03
    *  @Software : PyCharm
    ***********************************
    Masscan + Nmap扫描
"""
import json as serialize
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

from .. import tasks, forms, models

################################
# 端口扫描
################################
@login_required
@csrf_protect
def task_action(request):
    user = request.user
    error = ''
    asset_id_list = request.POST.get('asset_id_list')
    asset_id_list = serialize.loads(asset_id_list)
    if len(asset_id_list) == 0:
        error = '未选择符合要求资产'
    else:
        action = request.POST.get('action')
        if action == 'port':
            tasks.asset_port.delay(user.id, asset_id_list)
            error = '任务已提交'
        elif action == 'segment':
            tasks.asset_descover.delay(user.id, asset_id_list)
            error = '任务已提交'
        else:
            error = '参数错误'
    return JsonResponse(dict(error=error))

templates/AssetManage/assetlist.html
{% extends 'master.html' %}

{% block master %}
{% csrf_token %}
<div class="x-nav">
	<span class="layui-breadcrumb">
        <a href="">资产管理</a>
      </span>
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon layui-icon-refresh" style="line-height:30px"></i>
      </a>
</div>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <form class="layui-form layui-col-space5">
                        <div class="layui-input-inline layui-show-xs-block">
                            <input type="text" id="id_assetname" name="taskname" placeholder="资产名称" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-input-inline layui-show-xs-block">
                            <input type="text" id="id_assetkey" name="assetkey" placeholder="资产标识" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-input-inline layui-show-xs-block">
                            <select class="container" id="id_asset_type">
                                <option value="">资产类型</option>
                                {% for item in asset_type %}
                                    <option value="{{ item.id }}">{{ item.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </form>
                    <div class="layui-input-inline layui-show-xs-block UserTable">
                        <button class="layui-btn" data-type="reload" lay-submit="" lay-filter="sreach">
                            <i class="layui-icon">&#xe615;</i></button>
                    </div>
                </div>
                <xblock>
                    <div class="layui-card-header UserTable">
                        <div class="layui-col-md10">
                            <button class="layui-btn " data-type="deletechoice"><i class="layui-icon">&#xe640;</i>删除资产</button>
                            <button class="layui-btn" onclick="x_admin_show('资产申请', '{% url 'assetrequest' %}')"><i class="layui-icon layui-icon-download-circle"></i>资产申请</button>
                            <button class="layui-btn" onclick="x_admin_show('添加资产', '{% url 'assetcreate' %}')"><i class="layui-icon layui-icon-add-1"></i>新增资产</button>
                            <button class="layui-btn" onclick="x_admin_show('批量导入', '{% url 'createuploadcsv' %}')"><i class="layui-icon layui-icon-add-1"></i>批量导入</button>

                            <button class="layui-btn " data-type="portchoice"><i class="layui-icon">&#xe666;</i>端口扫描</button>
                            <button class="layui-btn " data-type="scanchoice"><i class="layui-icon">&#xe672;</i>安全扫描</button>
                            <!--
{#                            {% if user.is_superuser %}#}
                                <button class="layui-btn " data-type="descoverchoice"><i class="layui-icon">&#xe628;</i>资产发现</button>
                                <button class="layui-btn " data-type="assetuserchoice"><i class="layui-icon">&#xe601;</i>资产指定</button>
{#                            {% endif %}#}
                            -->
                        </div>
                    <!--
                        <div class='layui-col-md2' align='right'>
                            <div><a href="">os_csv模板</a>&<a href="">web_csv模板</a></div>
                            <div><a href="">vuln_csv模板</a></div>
                        </div>
                    -->
                    </div>
                </xblock>
                <!-- task table-->
                <div class="layui-card-body">
                    <table class="layui-table layui-form" id="asset_table" lay-filter="asset"></table>
                </div>
                <!--end task table-->
            </div>
        </div>
    </div>
</div>


<script>
var csrf = $('input[name="csrfmiddlewaretoken"]').val();

layui.use('table', function () {
    var table = layui.table;
    //方法级渲染
    table.render({
        elem: '#asset_table'
        ,url: "{% url 'assetlist' %}"
        ,method: 'post'
        ,where: {'csrfmiddlewaretoken':csrf}
        ,cols: [[
            {checkbox: true, fixed: true}
            ,{field: 'asset_id', title: '资产编号', sort: true, fixed:true}
            ,{field: 'asset_name', title: '资产名称'}
            ,{field: 'asset_key', title: '资产标识', sort: true, event:'Asset'}
            ,{field: 'asset_type', title: '资产分类', sort: true}
            ,{field: 'asset_status', title: '资产状态',sort: true}
            ,{field: 'asset_inuse', title: '认领状态'}
            ,{field: 'user_email', title: '管理人员'}
            ,{field: 'asset_updatetime', title: '更新时间',sort: true}
            ,{title: '高级选项', fixed: 'right', align:'center', toolbar: '#barDemo'}
        ]]
        ,id: 'testReload'
        ,page: true
        ,limit: 15
        ,text:{none: '目前暂无数据'}
    });
    // 高级选项
    table.on('tool(asset)', function (obj) {
        var data = obj.data.asset_id;
        if (obj.event === 'Asset'){
            {#//url = "{% url 'details' '0' %}";#}
            //url = url.replace(/0/,data);
            //x_admin_show('资产详情',url);
            alert(data)
        }else if(obj.event === 'edit'){
            url = "{% url 'assetupdate' 'key' %}";
            url = url.replace(/key/,data);
            x_admin_show('资产详情',url,600);
        }else if(obj.event === 'detail'){
            url = "{% url 'assetdetails' '0' %}";
            url = url.replace(/0/,data);
            window.open(url);
        }
    });

    // ***功能操作***
    var $ = layui.$, active = {
        // 删除
        deletechoice: function () { //获取选中数据
            var checkStatus = table.checkStatus('testReload')
                ,data = checkStatus.data
                ,list = new Array();
            for(var i=0;i<data.length;i++){
                list[i] = data[i].asset_id
            }
            layer.confirm('该操作为敏感操作<br>点击确认，将该选中任务移除', function (index) {
                $.post("{% url 'assetdelete' %}", {'asset_id_list':JSON.stringify(list), 'action':'delete', 'csrfmiddlewaretoken':csrf}, function (res) {
                    layer.msg(res.error);
                    setTimeout(function () {
                        location.replace(location.href)
                    }, 2000)
                })
            })
        }
        //端口扫描
        ,portchoice: function () { //获取选中数据
            var checkStatus = table.checkStatus('testReload')
                ,data = checkStatus.data
                ,list = new Array()
            for(var i=0;i<data.length;i++){
                list[i] = data[i].asset_id
            }
            // alert(JSON.stringify(list));
            layer.confirm('该操作为敏感操作<br>点击确认，将会对所选资产进行端口扫描', function (index) {
                $.post("{% url 'assettaskaction' %}", {'asset_id_list':JSON.stringify(list), 'action':'port', 'csrfmiddlewaretoken':csrf}, function (res) {
                    layer.msg(res.error);
                    setTimeout(function () {
                        location.replace(location.href)
                    }, 2000)
                })
            })
        }
        //安全扫描
        ,scanchoice: function () { //获取选中数据
            var checkStatus = table.checkStatus('testReload')
                ,data = checkStatus.data
                ,list = ';';
            for(var i=0;i<data.length;i++){
                list[i] = data[i].asset_id + ';'
            }
            url = "{% url 'taskscanchoice' 'key' %}";
            url = url.replace(/key/,list);
            x_admin_show('新建扫描',url,600);
        }
        // 执行重载
        ,reload: function () {
            table.reload('testReload',{
                page: {
                    curr:1      //重第一页开始
                }
                ,where: {
                    name : $('#id_assetname').val()
                    ,key : $('#id_assetkey').val()
                    ,type : $('#id_asset_type option:selected').val()
                }
            });
        }
    };
    $('.UserTable .layui-btn').on('click', function () {
        var type = $(this).data('type');
        active[type] ? active[type].call(this) : '';
    });
});
</script>

<script type="text/html" id="barDemo">
    <div class="layui-btn-group">
        <a class="layui-btn layui-btn-xs" lay-event="edit"><i class="layui-icon">&#xe642;</i>修改</a>
        <a class="layui-btn layui-btn-xs" lay-event="detail"><i class="layui-icon">&#xe60a;</i>详情</a>
    </div>
</script>
{% endblock %}

templates/AssetManage/assetrequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/AssetManage/asssetcreate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>